services:
  mongo:
    image: mongo:latest
    container_name: rtwm_mongo
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${ME_CONFIG_MONGODB_PORT}:${ME_CONFIG_MONGODB_PORT} 
    networks:
      - rtwm_network
    volumes:
      - ./data/mongo_db:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: rtwm_mongo_express
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME} 
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_MONGODB_PORT: ${ME_CONFIG_MONGODB_PORT} 
    ports:
      - 8081:8081
    networks:
      - rtwm_network
    depends_on:
      - mongo
  
  redis:
    image: redis:6.2-alpine
    container_name: rtwm_redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - rtwm_network

  grafana:
    image: grafana/grafana-enterprise
    container_name: rtwm_grafana
    restart: always
    # volumes:
    #  - ./data/grafana:/var/lib/grafana
    #  - /var/lib/grafana/plugins
    ports:
     - 3000:3000
    networks:
      - rtwm_network

networks:
  rtwm_network:
    name: rtwm_network
    driver: bridge